### ISSUE TITLE
Cannot find module 'roadhog/webpack'

### ISSUE THREAD

**Issue by lxlf** [umijs/umi-example-electron#1]
[1] Build failed: Cannot find module 'roadhog/webpack'
[1] { Error: Cannot find module 'roadhog/webpack'
[1]     at Function.Module._resolveFilename (module.js:536:15)
[1]     at Function.Module._load (module.js:466:25)
[1]     at Module.require (module.js:579:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/liuxi/Demo/umi-example-electron/webpack.config.js:2:1)
[1]     at Module._compile (module.js:635:30)
[1]     at Module._compile (/Users/liuxi/Demo/umi-example-electron/node_modules/pirates/lib/index.js:91:24)
[1]     at Module._extensions..js (module.js:646:10)
[1]     at Object.newLoader [as .js] (/Users/liuxi/Demo/umi-example-electron/node_modules/pirates/lib/index.js:96:7)
[1]     at Module.load (module.js:554:32)
[1]     at tryModuleLoad (module.js:497:12)
[1]     at Function.Module._load (module.js:489:3)
[1]     at Module.require (module.js:579:17)
[1]     at require (internal/module.js:11:18)
[1]     at applyWebpackConfig (/Users/liuxi/Demo/umi-example-electron/node_modules/af-webpack/lib/applyWebpackConfig.js:32:26)
[1]     at getConfig (/Users/liuxi/Demo/umi-example-electron/node_modules/af-webpack/lib/getConfig.js:504:53) code: 'MODULE_NOT_FOUND' }

**Comment by c2rlost2r** [comment]
just delete "roadhog/"
