### ISSUE TITLE
添加APP_ROOT后找不到自定义theme

### ISSUE THREAD

**Issue by canfeit** [umijs/umi-example-electron#6]
APP_ROOT=src/renderer  BROWSER=none umi dev
[0] Error: theme file don't exists
[0]     at _default (/Users/wuwei/GitHub/testwa/node_modules/af-webpack/lib/normalizeTheme.js:30:13)
[0]     at getConfig (/Users/wuwei/GitHub/testwa/node_modules/af-webpack/lib/getConfig.js:91:45)
[0]     at _default (/Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/getWebpackConfig.js:164:46)
[0]     at /Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/Service.js:203:59
[0]     at Generator.next (<anonymous>)
[0]     at step (/Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/Service.js:54:221)
[0]     at _next (/Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/Service.js:54:409)
[0]     at /Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/Service.js:54:477
[0]     at new Promise (<anonymous>)
[0]     at /Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/Service.js:54:97
[0]     at Service.dev (/Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/Service.js:263:7)
[0]     at Object.dev [as default] (/Users/wuwei/GitHub/testwa/node_modules/umi-build-dev/lib/dev.js:14:18)
[0]     at _default (/Users/wuwei/GitHub/testwa/node_modules/umi/lib/dev.js:23:50)
[0]     at Object.<anonymous> (/Users/wuwei/GitHub/testwa/node_modules/umi/lib/scripts/realDev.js:14:18)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by canfeit** [comment]
.webpackrc.js
`export default {
  theme: "./theme.js"
};
`

**Comment by nuaajiangteng** [comment]
> .webpackrc.js
> `export default { theme: "./theme.js" }; `

为什么我这么做没用，请问下你是怎么弄得
